name: build-bigpod

on:
  schedule:
    - cron: '12 00 * * *'  # 9:20pm everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.txt'
      
      
env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/bigpod98

jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      run: podman build . -t ghcr.io/bigpod98/bigpodsp/ubuntu:latest
    - name: login
      shell: bash
      run: podman login -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
      
